### ISSUE TITLE
Cleanup and simplify startup.

### ISSUE THREAD

**Issue by evanlinjin** [skycoin/cx#149]
### Synth's instructions from the **CX Readiness Group** on Telegram pertains:
 (as interpreted as @evanlinjin)

#### Part 1:
- [x] Make CX chain startup one command where one can configure the startup via command line arguments.

#### Part 2:
- [x] Create a new master public/private key and print them on command line in JSON.
- [x] Automatically run the master unless specified otherwise.
- [x] Print private key and address of the genesis address.
- [x] Print the blockchain hash/identifier.
- [ ] Print the dmsg public key for the node.

#### Part 3:
- [ ] Make sure CX Node shows up on cx-tracker.skycoin.com

### Summary:
- One command launching of a new CX Chain, with all parameters printed out on command line at launch.
- Automatic registration of new chain on tracker.
- CX Chain should run automatically as master node, unless specified otherwise.

### Later Steps:
- We should be able to compile and launch CX Chain from Skywire Visor menu (for existing or new chain).

**Comment by SkycoinSynth** [comment]
Moved to github.com/skycoin/cx-chains
