### ISSUE TITLE
Project Makefile

### ISSUE THREAD

**Issue by olemis** [skycoin/cx#149]
Targets

- [x] `build-parser` builds lexer and parser
- [x] `build` builds `cx` executable
- [x] `install` run `cx.sh`
- [x] `test` run tests
- [ ] `update-golden-files` generate golden files for
  * [ ] lexer token stream
  * ~parser test cases (AST ?)~
- [x] `help`
- [ ] Use `make` targets in Travis builds

**Comment by olemis** [comment]
Two pending items . Reopening this issue .

**Comment by evanlinjin** [comment]
**Part 1 Details:**
- [x] Extract tools from `cxgo`.
- [x] Refactor spaghetti code.
- [x] Remove dependence on `$GOPATH`.
- [x] Use `go mod` for dependency management.
